version: 2
jobs:
   one:
     docker:
       - image: google/cloud-sdk
     steps:
       - checkout
       - run: echo "A first hello"
       - run: gcloud auth activate-service-account circle-ci-connect@newsuk-datatech-dev-1251.iam.gserviceaccount.com  --key-file=$DEV_PROJECT_KEY
workflows:
   version: 2
   one_and_two:
     jobs:
       - one
