version: 2
jobs:
   one:
     docker:
       - image: google/cloud-sdk
     steps:
       - checkout
       - run: echo "A first hello"
       - run: echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
workflows:
   version: 2
   one_and_two:
     jobs:
       - one
