

version: 2

references:

  deps-cache-key: &deps-cache-key
    v6-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}

  repo-cache-key: &repo-cache-key
    v1-repo-{{ .Branch }}-{{ .Revision }}

  tox-cache-key: &tox-cache-key
    v1-tox-{{ .Branch }}-{{ checksum "tox.ini" }}

  container_config: &container_config
    docker:
      - image: circleci/python:3.7.4-stretch
    working_directory: ~/circle-ci-test

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - *repo-cache-key

  restore_dependecies: &restore_dependecies
    restore_cache:
      keys:
        - *deps-cache-key

  restore_tox_cache: &restore_tox_cache
    restore_cache:
      keys:
        - *tox-cache-key

jobs:

  checkout_code:
    <<: *container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: *repo-cache-key
          paths:
            - .
      - *restore_dependecies
      - run:
            name: Install Python deps in a venv
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install tox

      - save_cache:
          key:  *deps-cache-key
          paths:
            - "venv"

  unit_test_coverage_linting:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_dependecies
      - *restore_tox_cache
      - run:
            name: unit tests
            command: |
              . venv/bin/activate
              tox
      - save_cache:
            key:  *tox-cache-key
            paths:
              - ".tox"
      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

  linting:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_dependecies
      - run:
          name: linting checks
          command: |
            . venv/bin/activate
            flake8

  integration_test:
    docker:
      - image:   busybox:latest
    steps:
      - checkout
      - run:
          name: integration test
          command: echo "integration testing"

  build_artifacts:
    docker:
      - image:   busybox:latest
    steps:
      - checkout
      - run:
          name: build artifact
          command: echo "building artifacts"
  deploy:
    docker:
      - image:   busybox:latest
    steps:
      - checkout
      - run:
          name: integration test
          command: echo "integration testing"

  rsync:
    docker:
      - image: google/cloud-sdk
    steps:
      - run: echo $DEV_PROJECT_KEY | gcloud auth activate-service-account --key-file=-
      - run: gsutil ls gs://circleci_input
      - run: git clone https://github.com/mi-haque/circle-ci-test.git
      - run: gsutil rsync -r -d -x ".git/*" circle-ci-test/ gs://circleci_input

workflows:
  version: 2

  deployment_pipeline:
    jobs:
      - checkout_code:
          filters:
              branches:
                only:
                  - master
      - unit_test_coverage_linting:
          requires:
            - checkout_code
      - build_artifacts:
          requires:
            - unit_test_coverage_linting

      - wait_for_approval:
          type: approval
          requires:
              - build_artifacts
      - deploy:
          requires:
            - wait_for_approval