version: 2
jobs:
   one:
     docker:
       - image: google/cloud-sdk
     steps:
       - checkout
       - run: echo "A first hello"
       - run: echo $DEV_PROJECT_KEY | gcloud auth activate-service-account --key-file=-
       - run: gsutil ls gs://circleci_input
       - run: git clone https://github.com/mi-haque/circle-ci-test.git
       - run: gsutil rsync -r -d -x ".git/*" circle-ci-test/ gs://circleci_input
workflows:
   version: 2
   one_and_two:
     jobs:
       - one
