version: 2
jobs:
  build:
    docker:
      - image:   busybox:latest
    steps:
      - checkout
      - run:
          name: build repo
          command: echo "building..."

  unit_test:
    docker:
      - image: busybox:latest
      steps:
           - checkout
           -  run:
                name: unit tests
                command: echo "unit testing"

  linting:
    docker:
      - image: busybox:latest
    steps:
      - checkout
      - run:
          name: linting checks
          command: echo "linting & security checks happens here"

  integration_test:
    docker:
      - image: busybox:latest
      steps:
        name: integration test
        command: echo "integration testing"

  deploy:
    docker:
      - image: busybox:latest

  rsync:
    docker:
      - image: google/cloud-sdk
    steps:
      - run: echo $DEV_PROJECT_KEY | gcloud auth activate-service-account --key-file=-
      - run: gsutil ls gs://circleci_input
      - run: git clone https://github.com/mi-haque/circle-ci-test.git
      - run: gsutil rsync -r -d -x ".git/*" circle-ci-test/ gs://circleci_input

workflows:
  version: 2
  deployment_pipeline:

    jobs:
      - build
      - unit_test:
          requires:
              - build
      - linting:
          requires:
              - build
      - integration_test:
          requires:
              - build
      - deploy:
          requires:
            - linting
            - unit_test
            - integration_test
