version: 2
jobs:
   one:
     docker:
       - image: google/cloud-sdk
     steps:
       - checkout
       - run: echo "A first hello"
       - run: sleep 25
workflows:
   version: 2
   one_and_two:
     jobs:
       - one
